# 
# Production Mode
# 
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3.5'

services:

  vote:
    ports:
      - 80:80
    environment:
      PRODUCTION: 'true'

  redis:
    environment:
      TTL: '500'