version: '3.5'

services:

  vote:
    build: 
      context: ../vote
      dockerfile: Dockerfile
      args: 
        WORK_DIR: /var/www/app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_USER=
      - REDIS_PASS=
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-buster
    restart: always