version: '3.5'

services:

  vote:
    volumes:
      - ../vote:/var/www/app
    ports:
      - 3010:3000
      - 9227:9229
    environment:
      - NODE_ENV=development
      - PORT=3000

  redis:
    expose: 
      - 6379
